### ISSUE TITLE
Could you make a release of Multinomials @ 5b46e50 ?

### ISSUE THREAD

**Issue by erikmd** [math-comp/multinomials#14]
Hi @strub,
Would you agree to push a tag for Multinomials' commit 5b46e50983ee68dd1b6932e7e4a3bfc1113e7360 ?

Indeed this version of Multinomials compiles with MathComp 1.6.1+, [with Coq 8.5](https://travis-ci.org/CoqEAL/CoqEAL/jobs/298479845#L758) as well as [with Coq 8.6](https://travis-ci.org/CoqEAL/CoqEAL/jobs/298479844#L758) (an [issue](https://github.com/coq/coq/issues/6106) with Coq 8.7 being investigated) and @proux01 and I would like to prepare an opam package for ValidSDP, which relies on CoqEAL and Multinomials (see also the related PR CoqEAL/CoqEAL#6)

If you push such a tag, we propose to take care of preparing and submitting an opam package for Multinomials, relying on this tag and the appropriate versions of Coq/MathComp...

Kind regards,
Erik

**Comment by strub** [comment]
Hi,

I'm not sure to understand why you need a tag. There's a 1.6 branch and this branch is in maintenance mode (i.e. no big API changes & made to compile with the latest version of ssr 1.6.x). There is already an opam package for that branch (version 1.6.dev).

Regarding the issue with Coq 8.7, the issue is known and has been worked out in the master branch of finmap. I just updated the finmap copy of the 1.6 branch (I pushed the result in the temporary 1.6-8.7 branch) and made the multinomials library compiling with Coq 8.7. I'll check that it is still compiling with Coq 8.5 & 8.6 tomorrow (if you've time to check this during my night, feel free :) ).

Best. Pierre-Yves.

**Comment by erikmd** [comment]
Hi Pierre-Yves, thanks a lot for your reply.
> I'm not sure to understand why you need a tag.

We would like to make a *stable* opam package for validsdp in https://coq.inria.fr/opam/released, so a tag would be better than just a maintenance branch for that purpose...
I had proposed to tag 5b46e50 but indeed it would make sense to tag another commit in order to be compatible with the current release of Coq 8.7 as well.

> I just updated the finmap copy of the 1.6 branch (I pushed the result in the temporary 1.6-8.7 branch) and made the multinomials library compiling with Coq 8.7.

Thanks. I did a `git checkout 1.6-8.7` but I wasn't able to compile it with Coq 8.7 and MathComp 1.6.4, nor with Coq 8.6 or Coq 8.5 as I get:
```
File "./finmap/set.v", line 7, characters 15-20:
Error: Unable to locate library order with prefix mathcomp.
Makefile.coq:639: recipe for target 'finmap/set.vo' failed
```
Best regards. Erik

**Comment by strub** [comment]
Hi again,

The compilation issue for Coq 8.5/8.6 has been fixed (and pushed). For Coq 8.7, I'm waiting that ssreflect 1.6.4 has an opam package.

**Comment by maximedenes** [comment]
> The compilation issue for Coq 8.5/8.6 has been fixed (and pushed). For Coq 8.7, I'm waiting that ssreflect 1.6.4 has an opam package.

?

https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-mathcomp-ssreflect/coq-mathcomp-ssreflect.1.6.4

**Comment by strub** [comment]
Ah. I don't understand why I don't see it... (I did an opam update) I'll
investigate.

2017-11-08 13:25 GMT+01:00 Maxime Dénès <notifications@github.com>:

**Comment by maximedenes** [comment]
> I'm not sure to understand why you need a tag. There's a 1.6 branch and this branch is in maintenance mode (i.e. no big API changes & made to compile with the latest version of ssr 1.6.x). There is already an opam package for that branch (version 1.6.dev).

I think it is a bad practice to replace software releases with pointer to (moving) branches. The point of version numbers is to easily communicate around software (e.g. bug reports), and have an order on them (that doesn't require running `git`). Making packages for branches, whose build will by definition not be reproducible look like an even worse idea (at least when no stable package is provided).

My 2C.

**Comment by strub** [comment]
Forgot. My remote is a local path to a local clone of the repo. Sorry for
the noise.

2017-11-08 13:29 GMT+01:00 Pierre-Yves Strub <pierre-yves@strub.nu>:

**Comment by strub** [comment]
You should take the question at a global level. I made no release of that
library because I don't think the library is in a releasable state --- this
is why all the opam packages are tagged with "dev" --- and certainly
because I have been a bit lazy.

Some other library decided to take a dependency on it. Fine. Now, deciding
to make a release based on the git commit hash for which this external
project compiles, pushing it as an opam package (meaning that I'll have to
give some support for it) in IMO not a good choice. I have proposed Erik to
take a dependency on the 1.6 branch because this branch is really closed to
be released and I won't change the API level. Then, I was going to propose
to clean the 1.6.dev branch s.t. I can make a proper release with a proper
version number. You decided to throw your 2c coins a bit too soon :)

Currently, I'm making the project compiling with Coq 8.5 to 8.7 with ssr
1.6.


2017-11-08 13:29 GMT+01:00 Maxime Dénès <notifications@github.com>:

**Comment by maximedenes** [comment]
> I made no release of that
> library because I don't think the library is in a releasable state

Makes sense.

> Now, deciding
> to make a release based on the git commit hash for which this external
> project compiles, pushing it as an opam package (meaning that I'll have to
> give some support for it) in IMO not a good choice.

Indeed.

> Then, I was going to propose
> to clean the 1.6.dev branch s.t. I can make a proper release with a proper
> version number.

Sounds very good!

> You decided to throw your 2c coins a bit too soon :)

Not a big loss ;)

I must confess my message was influenced by what happens for instance in the EasyCrypt world, where the page mentioning "version 1.0" as the only supported one points to a moving branch (as far as I could tell). But that's another story. :)

**Comment by strub** [comment]
2017-11-08 14:04 GMT+01:00 Maxime Dénès <notifications@github.com>:

> I must confess my message was influenced by what happens for instance in
> the EasyCrypt world, where the page mentioning "version 1.0" as the only
> supported one points to a moving branch (as far as I could tell). But
> that's another story. :)
>
> Here, you're more hitting a problem of human resources on a highly moving
research project... the result is that EasyCrypt is not in a releasable
state (here for very good reasons) and it takes a lot of resources to bring
it into that state --- we are not Coq with dedicated persons in charge of
the release. Still, I agree with you, writing "1.0" on the webpage is silly
(I was against if you wan't to know :) ).

We should have a good news by the end of the year --- I decided to take
that time. From there, I'll enforce git branches, PR, CI, etc, etc... so
that we can release more often.

**Comment by maximedenes** [comment]
> Here, you're more hitting a problem of human resources on a highly moving
> research project...

Yeah I did not mean to say it was easy. That's very well understandable.

> We should have a good news by the end of the year --- I decided to take
> that time. From there, I'll enforce git branches, PR, CI, etc, etc... so
> that we can release more often.

Nice! I plan to have a look at it, hopping we can ~~steal your good ideas~~ exchange more ideas between Coq and EasyCrypt :)

I'll stop my digressions here, sorry about that :)

**Comment by erikmd** [comment]
Hi @strub,
> Now, deciding to make a release based on the git commit hash for which this external project compiles, pushing it as an opam package (meaning that I'll have to give some support for it) in IMO not a good choice.

Indeed on second thought my initial suggestion of tagging that commit was not a proper solution...

> I have proposed Erik to take a dependency on the 1.6 branch because this branch is really closed to be released and I won't change the API level. Then, I was going to propose to clean the 1.6.dev branch s.t. I can make a proper release with a proper version number.

Sounds great! thank you Pierre-Yves :)

**Comment by strub** [comment]
See coq/opam-coq-archive#221.
