### ISSUE TITLE
Notation level issue with toplevel coq

### ISSUE THREAD

**Issue by amahboubi** [math-comp/multinomials#21]
Not sure this problem is specific to the multinomial library, but I was unable to minimize.
I tried to use the multinomial library  bd25582 with Coq v8.8.2 in a console, in order to test my installation. I got the following error message:

```
 ledit coqtop
Welcome to Coq tepoztlan:/home/assia/Sources/coq,(HEAD detached at V8.8.2) (0ed45a5994bceea7c6b1d6530c72cd9ce29a46af)

Coq < From SsrMultinomials Require Import poly.
[Loading ML file ssrmatching_plugin.cmxs ... done]
[Loading ML file ssreflect_plugin.cmxs ... done]
[Loading ML file z_syntax_plugin.cmxs ... done]
[Loading ML file quote_plugin.cmxs ... done]
[Loading ML file newring_plugin.cmxs ... done]
Toplevel input, characters 0-42:
> From SsrMultinomials Require Import mpoly.
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error:
Level 2 is already declared right associative while it is now expected to be left associative.

Coq < 
```
I have no idea what happens here: library `mpoly` defines many notations at level 2, with `no` or `left` associativity (which is equivalent). But this is consistent with other usages  of that level, e.g. in mathcomp/ssreflect. Moreover, I get no error neither when executing the mpoly.v file itself in ProofGeneral nor when executing another file featuring the `Require Import`. Which means the issue has low priority for me, but still.

**Comment by strub** [comment]
Which version of mathcomp are you using

**Comment by amahboubi** [comment]
math-comp/math-comp@5f8d45b54aa98732ec3de43d91814459d5a2f2e4

**Comment by gares** [comment]
Could this be an instance of https://github.com/coq/coq/issues/9079
could you try to print the grammar and see if some stuff gets RIGHTA?

**Comment by strub** [comment]
@gares: could you be more explicit? What command should I run in which context? Thx.

**Comment by gares** [comment]
I think this command may help: https://coq.inria.fr/refman/user-extensions/syntax-extensions.html#coq:cmd.print-grammar-constr

If I'm right the problem is the following:
- each level can only have 1 associativity (left or right)
- Coq lets you declare notations (infix) at level X without associativity:
  + if that level is "virgin" then it is set to be right associative
  + if the level is already, say, left associative, then your notation becomes silently left associative
- Notations are added to the grammar as files are imported (the order matters)

Of course if you are always explicit about associativity you make your notation commands resilient to the order in which things are loaded. If you don't you risk your notation associativity to depend on the moon phase...

I'm not 100 sure, but it could be that you declare a notation at level 2 without giving an associativity. So Coq puts the level as right associative. Then you declare another one at level 2 asking for left and it breaks. IMHO the problem comes from the fact that @amahboubi loads the file in the void. If you load it after another library that sets level 2 as left associative, then your notation without an explicit associativity becomes magically left associative.

I hope it is now clear how messy it is ;-)

**Comment by strub** [comment]
So, when loading files from `coqtop`, level `2` was indeed bound to `right associativity`, even if level `2` is set to `left` in `ssrnotations`. Anyway, I force all level `2` notations to be left associative. This solved the issue.
